import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { fixture } from './helpers.mjs'; import { inspectAttestationManifestJson, verifyAttestationInline, verifyAttestationProof } from '../lib/attestation-proof.mjs'
const withRoot = async fn => { const root = await mkdtemp(join(tmpdir(), 'att-proof-')); try { return await fn(root) } finally { await rm(root, { recursive: true, force: true }) } }
test('inspects without filesystem access', async () => withRoot(async root => { const { manifest } = await fixture(root); assert.equal(inspectAttestationManifestJson(JSON.stringify(manifest)).filesystemAccess, false) }))
test('verifies signed subject and writes read-back checked content address', async () => withRoot(async root => { await fixture(root); const result = await verifyAttestationProof({ workspaceRoot: root, manifestPath: 'proof.json', artifactDir: 'artifacts' }); assert.equal(result.verdict, 'verified'); assert.equal(result.artifact.verifiedByReadBack, true); assert.equal(JSON.parse(await readFile(join(root, result.artifact.path), 'utf8')).verdict, 'verified') }))
test('replay is idempotent', async () => withRoot(async root => { await fixture(root); const a = await verifyAttestationProof({ workspaceRoot: root, manifestPath: 'proof.json', artifactDir: 'artifacts' }); const b = await verifyAttestationProof({ workspaceRoot: root, manifestPath: 'proof.json', artifactDir: 'artifacts' }); assert.equal(a.artifact.sha256, b.artifact.sha256) }))
test('rejects changed subject', async () => withRoot(async root => { await fixture(root); await writeFile(join(root, 'subject.bin'), 'tampered'); const result = await verifyAttestationProof({ workspaceRoot: root, manifestPath: 'proof.json', artifactDir: 'artifacts' }); assert.equal(result.verdict, 'rejected') }))
test('rejects envelope digest mismatch', async () => withRoot(async root => { await fixture(root); await writeFile(join(root, 'attestations/build.json'), '{}'); await assert.rejects(() => verifyAttestationProof({ workspaceRoot: root, manifestPath: 'proof.json', artifactDir: 'artifacts' }), { code: 'DIGEST_MISMATCH' }) }))
test('rejects path escape', async () => withRoot(async root => { const { manifest } = await fixture(root); manifest.subject.path = '../outside'; await writeFile(join(root, 'proof.json'), JSON.stringify(manifest)); await assert.rejects(() => verifyAttestationProof({ workspaceRoot: root, manifestPath: 'proof.json', artifactDir: 'artifacts' }), { code: 'PATH_ESCAPE' }) }))
test('inline MCP core verifies bounded public evidence without payload output', async () => withRoot(async root => { const { manifest, subject, pem, envelope } = await fixture(root); const result = await verifyAttestationInline({ manifestJson: JSON.stringify(manifest), subjectBase64: subject.toString('base64'), keysJson: JSON.stringify([{ id: 'release-key', pem }]), envelopesJson: JSON.stringify([{ id: 'build', envelope }]) }); assert.equal(result.verdict, 'verified'); assert.equal(result.returnsSignedPayloads, false); assert.ok(!JSON.stringify(result).includes(envelope.payload)) }))
test('secret-shaped manifest fields are rejected', async () => withRoot(async root => { const { manifest } = await fixture(root); manifest.apiToken = 'do-not-echo'; assert.throws(() => inspectAttestationManifestJson(JSON.stringify(manifest)), { code: 'INVALID_MANIFEST' }) }))
